### ISSUE TITLE
Textual content with images

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#69]
https://www.figma.com/file/yv0VtHTvMoGPqkv0RAYcVp/PDP?type=design&node-id=7499-38363&mode=dev
https://www.figma.com/file/Id3nd9kbfh8TpS1SfWhrW2/Volvo-Component-Library?type=design&node-id=1644-9421&mode=design&t=n3TLJTURs6cCslFe-4

- Content container
- Any text added before a heading in this block, is converted into a pre-title
- 4 images with caption (editors' responsibility on how many they add to look good)
- Only images are supported, not videos at the moment
- Caption below image
- On mobile and tablet, the content container is placed above 
- On mobile and tablet, the images are placed in a carousel which you swipe sideways to browse through
- On desktop, the content container is placed on the left
- On desktop, during scrolling, the content container will remain in position until all images have been scrolled past

**Comment by Andrei-Boiangiu** [comment]
Note: the pixel sizes differ from the figma design

**Comment by Andrei-Boiangiu** [comment]
repeoened with issue regarding Button in Mobile view #98

**Comment by Lakshmishri** [comment]
Can you retest this , as the issues with button is fixed

**Comment by Andrei-Boiangiu** [comment]
I can still see the issue with the button as commented on #98

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed 
 as tested on https://102-refactor-buttons--vg-volvotrucks-us-rd--netcentric.hlx.page/pdp
