### ISSUE TITLE
Bug - Major - Mobile view - iPhone - In-Page Navigation - The current selected section from the Subnav menu is not indicated by being bolded in the pop-up menu

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [Netcentric/vg-volvotrucks-us-rd#94]
Opening the In-Page Navigation menu on iPhone and selecting a section from it - the current selected section will not be indicated in the menu as being bolded

**Steps to reproduce:**
1. Open https://45-in-page-navigation--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/laura/inpage-navigation in iPhone view
2. Open the Subnav menu and select a section 
3. Open again the menu 
4. Notice that the current section that is selected and in view is not marked as active in the menu

**Expected result**
When selecting a current section from the Subnavigation menu, the currently selected section should be marked as active (bolded)

**Actual result**
the current selected section will not be indicated in the menu as being bolded on iPhone mobile view

**NOTE:**  This issue does not occur on Android mobile view

**Comment by Andrei-Boiangiu** [comment]
#45

**Comment by kesiah** [comment]
Solved in https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/95

**Comment by Andrei-Boiangiu** [comment]
on iPhone view the default selected Subnav section is indeed bolded - but due to #95 still present on iPhone view I cannot select any other Subnav section than the default selected one to check if the behavior applies also there

<img width="558" alt="image" src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/127409602/332f0d02-2d8a-4306-af49-02add64da155">


reopening and to be retested with the fix for iPhone view for #95

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed as tested on https://95-bug-inpagenavigation--vg-volvotrucks-us-rd--netcentric.hlx.page/pdp
